// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agvdsflijcweivxnxlbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFndmRzZmxpamN3ZWl2eG54bGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDMzOTgsImV4cCI6MjA1ODQ3OTM5OH0.SL1CZD4hc6S6ZW7pUgxOuKreZviG7eikxWGYLd2f4uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);